import React from 'react'
import { IoLocationSharp } from "react-icons/io5";
import { CiSearch } from "react-icons/ci";
import { LuLayoutDashboard } from "react-icons/lu";
import { AiOutlineUser } from "react-icons/ai";
import { LiaShoppingBagSolid } from "react-icons/lia";
import { RiArrowDropDownLine } from "react-icons/ri";
import { FaMicrophone } from "react-icons/fa6";
import logo from "../assets/logo.png"
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import { Autocomplete, TextField } from '@mui/material';



    const product_list= [
        {
            "quantity": "20",
            "price": 44999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5800,
            "variant_name": "Mi Notebook 14 Horizon - (8GB RAM / 512GB NVMe SSD / i7 10th Gen / Nvidia MX350) Gray",
            "actual_price": 44999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/MI_notebook_14_horizon_gray_image_bIopMEt.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 103,
            "other_variant_name": "8 GB",
            "stock_sataus": "In-stock",
            "id": 3489,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi Notebook 14 Horizon",
            "HSN": "8517",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:15:31.756632",
            "permission": 1,
            "slug": "mi-notebook-14-horizon",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 41999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5801,
            "variant_name": "Mi Notebook 14 Horizon - (8GB RAM / 512GB SSD / i5 10th Gen / Nvidia MX350) Gray",
            "actual_price": 41999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/MI_notebook_14_horizon_gray_image_jdx24Wk_V5eXc91.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 103,
            "other_variant_name": "8 GB",
            "stock_sataus": "In-stock",
            "id": 3489,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi Notebook 14 Horizon",
            "HSN": "8517",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:15:31.756632",
            "permission": 1,
            "slug": "mi-notebook-14-horizon",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "18",
            "price": 53999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5802,
            "variant_name": "Mi NoteBook Pro - Win 11 (16GB RAM / 512GB NVMe SSD / i5 11th Gen / Iris Xe Graphics) Lustrous Gray",
            "actual_price": 53999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/mi_notebook_pro_2_xON47Lq.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 104,
            "other_variant_name": "16 GB",
            "stock_sataus": "In-stock",
            "id": 3490,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Pro",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:00.552825",
            "permission": 1,
            "slug": "mi-notebook-pro",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 53999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5803,
            "variant_name": "Mi NoteBook Pro - Win 11 (16GB RAM / 512GB NVMe SSD / i5 11th Gen 11300H Processor / Iris Xe Graphics / MS Office 2021) Lustrous Gray",
            "actual_price": 53999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/mi_notebook_pro_2_8TW4iZi_c9lHgSO.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 104,
            "other_variant_name": "16 GB",
            "stock_sataus": "In-stock",
            "id": 3490,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Pro",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:00.552825",
            "permission": 1,
            "slug": "mi-notebook-pro",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "18",
            "price": 50999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5804,
            "variant_name": "Mi NoteBook Pro - Win 11 (8GB RAM / 512GB NVMe SSD / i5 11th Gen / Iris Xe Graphics / MS Office 2021) Lustrous Gray",
            "actual_price": 50999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/mi_notebook_pro_2_wBEnOP5_bLvQvRr.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 103,
            "other_variant_name": "8 GB",
            "stock_sataus": "In-stock",
            "id": 3490,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Pro",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:00.552825",
            "permission": 1,
            "slug": "mi-notebook-pro",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 50999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5805,
            "variant_name": "Mi NoteBook Pro - Win 11 (8GB RAM / 512GB NVMe SSD / i5 11th Gen / Iris Xe Graphics) Lustrous Gray",
            "actual_price": 50999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/mi_notebook_pro_2_5CNcSfK_XcfGWpI.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 103,
            "other_variant_name": "8 GB",
            "stock_sataus": "In-stock",
            "id": 3490,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Pro",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:00.552825",
            "permission": 1,
            "slug": "mi-notebook-pro",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 73999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5806,
            "variant_name": "Mi NoteBook Pro - Win 11 (16GB RAM / 512GB NVMe SSD / i7 11th Gen / Iris Xe Graphics - MS Office 2021) Lustrous Gray",
            "actual_price": 73999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/mi_notebook_pro_2_sbhVp7n_px1bMvP.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 104,
            "other_variant_name": "16 GB",
            "stock_sataus": "In-stock",
            "id": 3490,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Pro",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:00.552825",
            "permission": 1,
            "slug": "mi-notebook-pro",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 53999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5807,
            "variant_name": "Mi NoteBook Pro - Win 11 (16GB RAM / 512GB NVMe SSD / i5 11th Gen 11320H Processor / Iris Xe Graphics / MS Office 2021) Lustrous Gay",
            "actual_price": 53999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/mi_notebook_pro_rQaQT3j.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 104,
            "other_variant_name": "16 GB",
            "stock_sataus": "In-stock",
            "id": 3490,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Pro",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:00.552825",
            "permission": 1,
            "slug": "mi-notebook-pro",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 55999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5808,
            "variant_name": "Mi NoteBook Ultra - Win 11 (16GB RAM / 512GB NVMe SSD / i5 11th Gen / Iris Xe Graphics) Lustrous Gray",
            "actual_price": 55999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Mi_Notebook_Ultra_Image_wv5Nnhs.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 104,
            "other_variant_name": "16 GB",
            "stock_sataus": "In-stock",
            "id": 3491,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Ultra",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:33.111354",
            "permission": 1,
            "slug": "mi-notebook-ultra",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 53999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5809,
            "variant_name": "Mi NoteBook Ultra - Win 11 (8GB RAM / 512GB NVMe SSD / i5 11th Gen / Iris Xe Graphics / MS Office 2021) Lustrous Gray",
            "actual_price": 53999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Mi_Notebook_Ultra_Image_ltm2e7y_cyNkPzs.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 103,
            "other_variant_name": "8 GB",
            "stock_sataus": "In-stock",
            "id": 3491,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Ultra",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:33.111354",
            "permission": 1,
            "slug": "mi-notebook-ultra",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 53999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5810,
            "variant_name": "Mi NoteBook Ultra - Win 11 (8GB RAM / 512GB NVMe SSD / i5 11th Gen / Iris Xe Graphics) Lustrous Gray",
            "actual_price": 53999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Mi_Notebook_Ultra_Image_jA08lfi_yw8V1Qy.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 103,
            "other_variant_name": "8 GB",
            "stock_sataus": "In-stock",
            "id": 3491,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Ultra",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:33.111354",
            "permission": 1,
            "slug": "mi-notebook-ultra",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 77999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5811,
            "variant_name": "Mi NoteBook Ultra - Win 11 (16GB RAM / 512GB NVMe SSD / i7 11th Gen / Iris Xe Graphics / MS Office 2021) Lustrous Gray",
            "actual_price": 77999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Mi_Notebook_Ultra_Image_RM0bsSe_y9ehwf7.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 104,
            "other_variant_name": "16 GB",
            "stock_sataus": "In-stock",
            "id": 3491,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Ultra",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:33.111354",
            "permission": 1,
            "slug": "mi-notebook-ultra",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 77999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5812,
            "variant_name": "Mi NoteBook Ultra - Win 11 (16GB RAM / 512GB NVMe SSD / i7 11th Gen / Iris Xe Graphics) Lustrous Gray",
            "actual_price": 77999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Mi_Notebook_Ultra_Image_LupeBq5_x8qRYU7.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 104,
            "other_variant_name": "16 GB",
            "stock_sataus": "In-stock",
            "id": 3491,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Ultra",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:33.111354",
            "permission": 1,
            "slug": "mi-notebook-ultra",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 55999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5813,
            "variant_name": "Mi NoteBook Ultra - Win 11 (16GB RAM / 512GB NVMe SSD / i5 11th Gen 11320H Processor / Iris Xe Graphics / MS Office 2021) Lustrous Gray",
            "actual_price": 55999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/notebook_ultra_e5wgESy.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 104,
            "other_variant_name": "16 GB",
            "stock_sataus": "In-stock",
            "id": 3491,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Ultra",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:33.111354",
            "permission": 1,
            "slug": "mi-notebook-ultra",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 55999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5814,
            "variant_name": "Mi NoteBook Ultra - Win 11 (16GB RAM / 512GB NVMe SSD / i5 11th Gen 11300H Processor / Iris Xe Graphics / MS Office 2021) Lustrous Gray",
            "actual_price": 55999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Mi_Notebook_Ultra_Image_itp8YQa_ZLIhe8o.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 104,
            "other_variant_name": "16 GB",
            "stock_sataus": "In-stock",
            "id": 3491,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Mi NoteBook Ultra",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:33.111354",
            "permission": 1,
            "slug": "mi-notebook-ultra",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 71999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5815,
            "variant_name": "Xiaomi Notebook Pro 120G - (16GB RAM / 512GB PCIe Gen 4.0 / i5 12th Gen / Nvidia MX550) Gray",
            "actual_price": 71999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Xiamoi_Notebook_Pro_120G_image_amvCzWn.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 104,
            "other_variant_name": "16 GB",
            "stock_sataus": "In-stock",
            "id": 3492,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Xiaomi Notebook Pro 120G",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:41.944696",
            "permission": 1,
            "slug": "xiaomi-notebook-pro-120g",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 67999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5816,
            "variant_name": "Xiaomi Notebook Pro 120G - (16GB RAM / 512GB PCIe Gen 4.0 / i5 12th Gen / UHD Graphics) Gray",
            "actual_price": 67999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/NOTEBOOK_PRO_120G_IMAGE_yl4F0NP.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 104,
            "other_variant_name": "16 GB",
            "stock_sataus": "In-stock",
            "id": 3492,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "Xiaomi Notebook Pro 120G",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:41.944696",
            "permission": 1,
            "slug": "xiaomi-notebook-pro-120g",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 219,
            "brand_name": "Xiaomi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 44990.0,
            "whishlist_status": "Login Required",
            "variant_id": 5817,
            "variant_name": "RedmiBook 15 - (i3 11th Gen / 8 GB / 512 GB SSD / Windows 10 Home) Thin and Light Laptop (15.6 Inch, Charcoal Gray, 1.8 kg, With MS Office)",
            "actual_price": 44990.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/RedmiBook-15-e-Learning-Edition-Intel-Core-i3-JYU4367IN-Charcoal-Grey-1_gaAIjL1.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 103,
            "other_variant_name": "8 GB",
            "stock_sataus": "In-stock",
            "id": 3493,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "RedmiBook 15",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:51.429549",
            "permission": 1,
            "slug": "redmibook-15",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 222,
            "brand_name": "Redmi",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 41999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5818,
            "variant_name": "RedmiBook 15 Pro - (i8GB RAM / 512GB SSD / i5 11th Gen / Iris Xe Graphics) Charcoal Gray",
            "actual_price": 41999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Redmi_book_15_pro_image_9pDRB9M.jpg",
            "color_variant_id": 1596,
            "color_variant_name": "Grey",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": 103,
            "other_variant_name": "8 GB",
            "stock_sataus": "In-stock",
            "id": 3494,
            "Meta_Title": "nan",
            "Meta_Keyword": "nan",
            "Meta_Description": "nan",
            "title": "RedmiBook 15 Pro",
            "HSN": "8517",
            "description": "nan",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:16:47.314216",
            "permission": 1,
            "slug": "redmibook-15-pro",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 177,
            "sub_category": "Traditional laptops",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 222,
            "brand_name": "Redmi",
            "store_id": 1
        },
        {
            "quantity": "14",
            "price": 3399.0,
            "whishlist_status": "Login Required",
            "variant_id": 5905,
            "variant_name": "SanDisk Ultra Dual Drive Go USB Type-C 512 GB OTG Drive  (Green, Type A to Type C)",
            "actual_price": 3399.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/SANDISK_ULTRA_DUAL_DRIVE_GO_USB_GREEN_oPRiJJo_06jr0N6.jpg",
            "color_variant_id": 1604,
            "color_variant_name": "Green ",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3542,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Dual Drive Go USB Type-C",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T18:00:38.067491",
            "permission": 1,
            "slug": "sandisk-ultra-dual-drive-go-usb-type-c",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "8",
            "price": 1799.0,
            "whishlist_status": "Login Required",
            "variant_id": 5906,
            "variant_name": "SanDisk Ultra Dual Drive Go USB Type-C 256 GB OTG Drive  (Green, Type A to Type C)",
            "actual_price": 1799.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/SANDISK_ULTRA_DUAL_DRIVE_GO_USB_GREEN_tnm4p8w_mpSD2hw.jpg",
            "color_variant_id": 1604,
            "color_variant_name": "Green ",
            "storage_variant_id": 199,
            "storage_variant_name": "256 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3542,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Dual Drive Go USB Type-C",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T18:00:38.067491",
            "permission": 1,
            "slug": "sandisk-ultra-dual-drive-go-usb-type-c",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "10",
            "price": 998.0,
            "whishlist_status": "Login Required",
            "variant_id": 5907,
            "variant_name": "SanDisk Ultra Dual Drive Go USB Type-C 128 GB OTG Drive  (Green, Type A to Type C)",
            "actual_price": 998.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/SANDISK_ULTRA_DUAL_DRIVE_GO_USB_GREEN_D7uaq4g_3ANP0hj.jpg",
            "color_variant_id": 1604,
            "color_variant_name": "Green ",
            "storage_variant_id": 200,
            "storage_variant_name": "128 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3542,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Dual Drive Go USB Type-C",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T18:00:38.067491",
            "permission": 1,
            "slug": "sandisk-ultra-dual-drive-go-usb-type-c",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "4",
            "price": 659.0,
            "whishlist_status": "Login Required",
            "variant_id": 5908,
            "variant_name": "SanDisk Ultra Dual Drive Go USB Type-C 64 GB OTG Drive  (Green, Type A to Type C)",
            "actual_price": 659.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/SANDISK_ULTRA_DUAL_DRIVE_GO_USB_GREEN_J0u7AQg_mc1VRvj.jpg",
            "color_variant_id": 1604,
            "color_variant_name": "Green ",
            "storage_variant_id": 201,
            "storage_variant_name": "64 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3542,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Dual Drive Go USB Type-C",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T18:00:38.067491",
            "permission": 1,
            "slug": "sandisk-ultra-dual-drive-go-usb-type-c",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "18",
            "price": 755.0,
            "whishlist_status": "Login Required",
            "variant_id": 5909,
            "variant_name": "SanDisk Ultra Dual Drive Go USB Type-C 32 GB OTG Drive  (Green, Type A to Type C)",
            "actual_price": 755.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/SANDISK_ULTRA_DUAL_DRIVE_GO_USB_GREEN_g95CYEf.jpg",
            "color_variant_id": 1604,
            "color_variant_name": "Green ",
            "storage_variant_id": 204,
            "storage_variant_name": "32 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3542,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Dual Drive Go USB Type-C",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T18:00:38.067491",
            "permission": 1,
            "slug": "sandisk-ultra-dual-drive-go-usb-type-c",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "10",
            "price": 3398.0,
            "whishlist_status": "Login Required",
            "variant_id": 5910,
            "variant_name": "SanDisk Ultra Dual Drive Go USB Type-C 512 GB OTG Drive  (Blue, Type A to Type C)",
            "actual_price": 3398.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Sandisk_Ultra_Dual_Drive_Go_USB_-_BLUE_7uuvdzX_52efaZp.jpg",
            "color_variant_id": 1603,
            "color_variant_name": "Blue",
            "storage_variant_id": 181,
            "storage_variant_name": "512 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3542,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Dual Drive Go USB Type-C",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T18:00:38.067491",
            "permission": 1,
            "slug": "sandisk-ultra-dual-drive-go-usb-type-c",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 1799.0,
            "whishlist_status": "Login Required",
            "variant_id": 5911,
            "variant_name": "SanDisk Ultra Dual Drive Go USB Type-C 256 GB OTG Drive  (Blue, Type A to Type C)",
            "actual_price": 1799.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Sandisk_Ultra_Dual_Drive_Go_USB_-_BLUE_4fw8CVr_KtxfHfZ.jpg",
            "color_variant_id": 1603,
            "color_variant_name": "Blue",
            "storage_variant_id": 199,
            "storage_variant_name": "256 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3542,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Dual Drive Go USB Type-C",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T18:00:38.067491",
            "permission": 1,
            "slug": "sandisk-ultra-dual-drive-go-usb-type-c",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "18",
            "price": 999.0,
            "whishlist_status": "Login Required",
            "variant_id": 5912,
            "variant_name": "SanDisk Ultra Dual Drive Go USB Type-C 128 GB OTG Drive  (Blue, Type A to Type C)",
            "actual_price": 999.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Sandisk_Ultra_Dual_Drive_Go_USB_-_BLUE_pJ1K0U4_pQNMtof.jpg",
            "color_variant_id": 1603,
            "color_variant_name": "Blue",
            "storage_variant_id": 200,
            "storage_variant_name": "128 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3542,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Dual Drive Go USB Type-C",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T18:00:38.067491",
            "permission": 1,
            "slug": "sandisk-ultra-dual-drive-go-usb-type-c",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 833.0,
            "whishlist_status": "Login Required",
            "variant_id": 5913,
            "variant_name": "SanDisk Ultra Dual Drive Go USB Type-C 64 GB OTG Drive  (Blue, Type A to Type C)",
            "actual_price": 833.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Sandisk_Ultra_Dual_Drive_Go_USB_-_BLUE_mvinlGa_qva1eCV.jpg",
            "color_variant_id": 1603,
            "color_variant_name": "Blue",
            "storage_variant_id": 201,
            "storage_variant_name": "64 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3542,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Dual Drive Go USB Type-C",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T18:00:38.067491",
            "permission": 1,
            "slug": "sandisk-ultra-dual-drive-go-usb-type-c",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 799.0,
            "whishlist_status": "Login Required",
            "variant_id": 5914,
            "variant_name": "SanDisk Ultra Dual Drive Go USB Type-C 32 GB OTG Drive  (Blue, Type A to Type C)",
            "actual_price": 799.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/Sandisk_Ultra_Dual_Drive_Go_USB_-_BLUE_y9UEX5e.jpg",
            "color_variant_id": 1603,
            "color_variant_name": "Blue",
            "storage_variant_id": 204,
            "storage_variant_name": "32 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3542,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Dual Drive Go USB Type-C",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T18:00:38.067491",
            "permission": 1,
            "slug": "sandisk-ultra-dual-drive-go-usb-type-c",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "10",
            "price": 6898.0,
            "whishlist_status": "Login Required",
            "variant_id": 5915,
            "variant_name": "Sandisk Portable 1TB SSD",
            "actual_price": 6898.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/sandisk_portable_ssd_image_sRPXdTT.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": "",
            "storage_variant_name": "",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3543,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Portable SSD",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:18:34.330385",
            "permission": 1,
            "slug": "sandisk-portable-ssd",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 181,
            "sub_category": "Solid state drives (ssd)",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "10",
            "price": 6019.0,
            "whishlist_status": "Login Required",
            "variant_id": 5916,
            "variant_name": "Sandisk Portable 480GB SSD",
            "actual_price": 6019.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/sandisk_portable_ssd_image.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": "",
            "storage_variant_name": "",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3543,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Portable SSD",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:18:34.330385",
            "permission": 1,
            "slug": "sandisk-portable-ssd",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 181,
            "sub_category": "Solid state drives (ssd)",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "10",
            "price": 15598.0,
            "whishlist_status": "Login Required",
            "variant_id": 5917,
            "variant_name": "Sandisk Extreme Portable 2TB SSD",
            "actual_price": 15598.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/extreme_portable_ssd_image_ssiD713.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": "",
            "storage_variant_name": "",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3544,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Extreme Portable SSD",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:19:01.443821",
            "permission": 1,
            "slug": "sandisk-extreme-portable-ssd",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 181,
            "sub_category": "Solid state drives (ssd)",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "10",
            "price": 9499.0,
            "whishlist_status": "Login Required",
            "variant_id": 5918,
            "variant_name": "Sandisk Extreme Portable 1TB SSD",
            "actual_price": 9499.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/extreme_portable_ssd_image_XMwrUTu.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": "",
            "storage_variant_name": "",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3544,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Extreme Portable SSD",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:19:01.443821",
            "permission": 1,
            "slug": "sandisk-extreme-portable-ssd",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 181,
            "sub_category": "Solid state drives (ssd)",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "10",
            "price": 7299.0,
            "whishlist_status": "Login Required",
            "variant_id": 5919,
            "variant_name": "Sandisk Extreme Portable 500GB SSD",
            "actual_price": 7299.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/extreme_portable_ssd_image.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": "",
            "storage_variant_name": "",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3544,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Extreme Portable SSD",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:19:01.443821",
            "permission": 1,
            "slug": "sandisk-extreme-portable-ssd",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 181,
            "sub_category": "Solid state drives (ssd)",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "10",
            "price": 21099.0,
            "whishlist_status": "Login Required",
            "variant_id": 5920,
            "variant_name": "Sandisk Extreme Pro Portable 2TB SSD",
            "actual_price": 21099.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/SanDisk-Extreme-Pro_Portable_SSD_Image_0Vpeq8T.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": "",
            "storage_variant_name": "",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3545,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Extreme Pro Portable SSD",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:19:20.631931",
            "permission": 1,
            "slug": "sandisk-extreme-pro-portable-ssd",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 181,
            "sub_category": "Solid state drives (ssd)",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "10",
            "price": 13566.0,
            "whishlist_status": "Login Required",
            "variant_id": 5921,
            "variant_name": "Sandisk Extreme Pro Portable 1TB SSD",
            "actual_price": 13566.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/SanDisk-Extreme-Pro_Portable_SSD_Image.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": "",
            "storage_variant_name": "",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3545,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Extreme Pro Portable SSD",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-18T19:19:20.631931",
            "permission": 1,
            "slug": "sandisk-extreme-pro-portable-ssd",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 181,
            "sub_category": "Solid state drives (ssd)",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 329.0,
            "whishlist_status": "Login Required",
            "variant_id": 5922,
            "variant_name": "SanDisk Cruzer Force USB Flash Drive 32GB Pen Drive",
            "actual_price": 329.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/SANDISK_CRUZER_FORCE_USB_IMAGE_4K9VlyP_t9gRskd.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": 204,
            "storage_variant_name": "32 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3546,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Cruzer Force USB Flash Drive",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T15:20:32.364664",
            "permission": 1,
            "slug": "sandisk-cruzer-force-usb-flash-drive",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 299.0,
            "whishlist_status": "Login Required",
            "variant_id": 5923,
            "variant_name": "SanDisk Cruzer Force USB Flash Drive 16GB Pen Drive",
            "actual_price": 299.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/SANDISK_CRUZER_FORCE_USB_IMAGE_luYCCtH.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": 205,
            "storage_variant_name": "16 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3546,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Cruzer Force USB Flash Drive",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T15:20:32.364664",
            "permission": 1,
            "slug": "sandisk-cruzer-force-usb-flash-drive",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 1709.0,
            "whishlist_status": "Login Required",
            "variant_id": 5924,
            "variant_name": "SanDisk Ultra Flair USB 3.0 256GB Flash Drive",
            "actual_price": 1709.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/sandisk_ultra_flair_usb_3_derHc7o_JiNJwCG.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": 199,
            "storage_variant_name": "256 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3547,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Flair 3.0 USB Flash Drive",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T15:58:16.163931",
            "permission": 1,
            "slug": "sandisk-ultra-flair-30-usb-flash-drive",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "40",
            "price": 859.0,
            "whishlist_status": "Login Required",
            "variant_id": 5925,
            "variant_name": "SanDisk Ultra Flair USB 128GB 3.0 Flash Drive",
            "actual_price": 859.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/sandisk_ultra_flair_usb_3_3CNp0Kf_PaR1uma.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": 200,
            "storage_variant_name": "128 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3547,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Flair 3.0 USB Flash Drive",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T15:58:16.163931",
            "permission": 1,
            "slug": "sandisk-ultra-flair-30-usb-flash-drive",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 479.0,
            "whishlist_status": "Login Required",
            "variant_id": 5926,
            "variant_name": "SanDisk Ultra Flair USB 3.0 64GB Flash Drive",
            "actual_price": 479.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/sandisk_ultra_flair_usb_3_xDhSy93_cCMTmgD.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": 201,
            "storage_variant_name": "64 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3547,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Flair 3.0 USB Flash Drive",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T15:58:16.163931",
            "permission": 1,
            "slug": "sandisk-ultra-flair-30-usb-flash-drive",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        },
        {
            "quantity": "20",
            "price": 379.0,
            "whishlist_status": "Login Required",
            "variant_id": 5927,
            "variant_name": "SanDisk Ultra Flair USB 3.0 32GB Flash Drive",
            "actual_price": 379.0,
            "image": "https://crazzyhub.s3.amazonaws.com/media/product_variant/sandisk_ultra_flair_usb_3_LZnoQ5M.jpg",
            "color_variant_id": "",
            "color_variant_name": "",
            "storage_variant_id": 204,
            "storage_variant_name": "32 GB",
            "other_variant_id": "",
            "other_variant_name": "",
            "stock_sataus": "In-stock",
            "id": 3547,
            "Meta_Title": "",
            "Meta_Keyword": "",
            "Meta_Description": "",
            "title": "Sandisk Ultra Flair 3.0 USB Flash Drive",
            "HSN": "85235100",
            "description": "NA",
            "arriving_soon": false,
            "show_for_user": true,
            "is_bestseller": false,
            "admin_permission": "Approved",
            "lastedit_date": "2023-07-26T15:58:16.163931",
            "permission": 1,
            "slug": "sandisk-ultra-flair-30-usb-flash-drive",
            "main_category_id": 27,
            "main_category": "Laptop & Accessories",
            "sub_category_id": 178,
            "sub_category": "Pen drive",
            "sub_sub_category_id": "",
            "sub_sub_category": "",
            "brand_id": 223,
            "brand_name": "Sandisk",
            "store_id": 1
        }
    ]

const HomeNav = () => {

    const navigate = useNavigate()
    const handle2=()=> {

        toast("this is my about page")

        navigate("/abouts")


    }

    

    const handle3=()=>{
        navigate("/home")
    }

    const hello=()=>{
        navigate("/login")
    }
  return (
    <div className='lg:w-full sticky top-0 z-50  lg:h-full'>
    <div className='flex lg:flex-row flex-col  bg-white shadow-md shadow-gray-300   lg:px-40 lg:pt-0 lg:w-full   gap-x-2 lg:py-0  py-3 items-center'>
        <div className=' h-full w-auto lg:block hidden'>
            <img className='h-[15vh] w-full' onClick={handle3} src={logo} alt=""></img>
        </div>
        <div className='lg:w-[20%] w-full  lg:pt-5.5 '>
            <p className='font-bold'><IoLocationSharp className='inline-block' /> Delivering to <RiArrowDropDownLine  className='inline-block text-2xl' /></p>
            <p className='lg:pl-0 pl-3'>Sitapur Road, Abbas Nagar, Bakshi Ka Talab</p>
        </div>
        <div className=' lg:w-[46%] w-[95%] lg:mx-0 mx-3 relative  lg:pt-5'>
            {/* <CiSearch className='absolute text-2xl lg:top-9 top-3 left-5  text-gray-600' /> */}
            <Autocomplete
  className="!w-full"
  disablePortal
  options={
    product_list?.map((i) => ({
      label: i?.variant_name, // Display text
      image: i?.image, // Include image in data
    })) || []
  }
  sx={{ width: 300 }}

  renderOption={(props, option) => (
    <div  {...props}>
      <img src={option.image} alt={option.label} width="30" height="30" style={{ marginRight: 10 }} />
      {option.label}
    </div>
  )}
  renderInput={(params) => <TextField {...params} label="Search" type="text" />}
/>

                
         <button className='px-2 py-2 bg-transparent border lg:hidden  absolute text-2xl  rounded-xl  lg:top-6 top-2   left-[82%]'><FaMicrophone className=" " /></button>
        </div>
        <div className=' lg:block hidden  text-3xl  mt-5 gap-5 ml-5 '>
        <div className='flex gap-5 '>
        <LuLayoutDashboard onClick={()=> navigate("/details")}  />
        <AiOutlineUser onClick={hello} />
        <LiaShoppingBagSolid onClick={handle2}  />
        </div>

        </div>
    </div>
</div>
  )
}

export default HomeNav
