import { Button, Drawer } from "@mui/material";
import React, { useState } from "react";

const Mobile = () => {
  const product_list = [
    {
      quantity: "50",
      price: 15990.0,
      whishlist_status: "Login Required",
      variant_id: 5275,
      variant_name: "vivo T1 5G (Starlight Black, 128 GB)  (4 GB RAM)",
      actual_price: 15990.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/New_Project_46_2GUElU1.jpg",
      color_variant_id: 1421,
      color_variant_name: "Starlight Black",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 97,
      other_variant_name: "4 GB",
      stock_sataus: "In-stock",
      id: 3318,
      Meta_Title: "vivo T1 5G",
      Meta_Keyword: "vivo T1 5G",
      Meta_Description: "vivo T1 5G",
      title: "vivo T1 5G",
      HSN: "18999",
      description: "vivo T1 5G",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-09T19:05:41.358677",
      permission: 1,
      slug: "vivo-t1-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "50",
      price: 15990.0,
      whishlist_status: "Login Required",
      variant_id: 5277,
      variant_name: "vivo T1 5G (Rainbow Fantasy, 128 GB)  (4 GB RAM)",
      actual_price: 15990.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Crazzyhub_images_1_c1APxjy.jpg",
      color_variant_id: 1444,
      color_variant_name: "Rainbow Fantastic ",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 97,
      other_variant_name: "4 GB",
      stock_sataus: "In-stock",
      id: 3318,
      Meta_Title: "vivo T1 5G",
      Meta_Keyword: "vivo T1 5G",
      Meta_Description: "vivo T1 5G",
      title: "vivo T1 5G",
      HSN: "18999",
      description: "vivo T1 5G",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-09T19:05:41.358677",
      permission: 1,
      slug: "vivo-t1-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "50",
      price: 24999.0,
      whishlist_status: "Login Required",
      variant_id: 5278,
      variant_name: "vivo T1 Pro 5G (Turbo Cyan, 128 GB)  (8 GB RAM)",
      actual_price: 24999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-t1-pro-5g-turbo-cyan-128gb-8gb-ram-Front-Back-View_JN7AAED.webp",
      color_variant_id: 1652,
      color_variant_name: "Turbo Cyan",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 96,
      other_variant_name: "8 GB",
      stock_sataus: "In-stock",
      id: 3319,
      Meta_Title: "vivo T1 Pro 5G",
      Meta_Keyword: "vivo T1 Pro 5G",
      Meta_Description: "vivo T1 Pro 5G",
      title: "vivo T1 Pro 5G",
      HSN: "18999",
      description: "vivo T1 Pro 5G",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-06T12:33:59.100537",
      permission: 1,
      slug: "vivo-t1-pro-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "50",
      price: 24999.0,
      whishlist_status: "Login Required",
      variant_id: 5279,
      variant_name: "vivo T1 Pro 5G (Turbo Black, 128 GB)  (8 GB RAM)",
      actual_price: 24999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-t1-pro-5g-turbo-black-128gb-8gb-ram-Front-Back-View_XQt5E1p.webp",
      color_variant_id: 1446,
      color_variant_name: "Turbo Black ",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 96,
      other_variant_name: "8 GB",
      stock_sataus: "In-stock",
      id: 3319,
      Meta_Title: "vivo T1 Pro 5G",
      Meta_Keyword: "vivo T1 Pro 5G",
      Meta_Description: "vivo T1 Pro 5G",
      title: "vivo T1 Pro 5G",
      HSN: "18999",
      description: "vivo T1 Pro 5G",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-06T12:33:59.100537",
      permission: 1,
      slug: "vivo-t1-pro-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "0",
      price: 11999.0,
      whishlist_status: "Login Required",
      variant_id: 5280,
      variant_name: "vivo T1X (Space Blue, 64 GB)  (4 GB RAM)",
      actual_price: 11999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/New_Project_33_m2L399z.jpg",
      color_variant_id: 1633,
      color_variant_name: "Space Blue",
      storage_variant_id: 169,
      storage_variant_name: "64 GB",
      other_variant_id: 97,
      other_variant_name: "4 GB",
      stock_sataus: "Out-stock",
      id: 3320,
      Meta_Title: "vivo T1X",
      Meta_Keyword: "vivo T1X",
      Meta_Description: "vivo T1X",
      title: "vivo T1X",
      HSN: "85171290",
      description: "vivo T1X",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2023-10-27T16:18:55.705193",
      permission: 1,
      slug: "vivo-t1x",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "0",
      price: 11999.0,
      whishlist_status: "Login Required",
      variant_id: 5281,
      variant_name: "vivo T1X (Gravity Black, 64 GB)  (4 GB RAM)",
      actual_price: 11999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Crazzyhub_images_41.jpg",
      color_variant_id: 1447,
      color_variant_name: "Gravity Black ",
      storage_variant_id: 169,
      storage_variant_name: "64 GB",
      other_variant_id: 97,
      other_variant_name: "4 GB",
      stock_sataus: "Out-stock",
      id: 3320,
      Meta_Title: "vivo T1X",
      Meta_Keyword: "vivo T1X",
      Meta_Description: "vivo T1X",
      title: "vivo T1X",
      HSN: "85171290",
      description: "vivo T1X",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2023-10-27T16:18:55.705193",
      permission: 1,
      slug: "vivo-t1x",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "50",
      price: 20499.0,
      whishlist_status: "Login Required",
      variant_id: 5335,
      variant_name: "vivo Y100 5G (Pacific Blue, 128 GB)  (8 GB RAM)",
      actual_price: 20499.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo_Y100_qWwbZsi.jpg",
      color_variant_id: 1475,
      color_variant_name: "Pacific Blue",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 96,
      other_variant_name: "8 GB",
      stock_sataus: "In-stock",
      id: 3344,
      Meta_Title: "VIVO Y100 ",
      Meta_Keyword: "VIVO Y100 ",
      Meta_Description: "VIVO Y100 ",
      title: "VIVO Y100 ",
      HSN: "8517",
      description:
        "The Vivo Y100 5G features colour-changing fluorite AG glass that changes colour with changes in environment and time. The 64 MP OIS anti-shake camera helps to take steady and cinematic images without any hassle. This smartphone has 8 GB RAM with an additional 8 GB of extended RAM, which allows you to keep up to 27 apps in the background. It uses a powerful MediaTek Dimensity 900 processor to give you a smooth 5G experience, and its 4500 mAh battery with 44 W FlashCharge lets the phone’s battery last for a long time This smartphone has many camera features, so you can create vlogs, movies, and click portraits as you desire. The Funtouch OS 13, allows you to have a secure OS experience, in addition to that you can also enjoy personalised settings, privacy protection, and much more.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-01-07T19:40:36.422545",
      permission: 1,
      slug: "vivo-y100",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 20499.0,
      whishlist_status: "Login Required",
      variant_id: 5336,
      variant_name: "vivo Y100 5G (Metal Black, 128 GB) (8 GB RAM)",
      actual_price: 20499.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-Y100-Mobile-Phone.jpg",
      color_variant_id: 1476,
      color_variant_name: "Metal Black",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 96,
      other_variant_name: "8 GB",
      stock_sataus: "In-stock",
      id: 3344,
      Meta_Title: "VIVO Y100 ",
      Meta_Keyword: "VIVO Y100 ",
      Meta_Description: "VIVO Y100 ",
      title: "VIVO Y100 ",
      HSN: "8517",
      description:
        "The Vivo Y100 5G features colour-changing fluorite AG glass that changes colour with changes in environment and time. The 64 MP OIS anti-shake camera helps to take steady and cinematic images without any hassle. This smartphone has 8 GB RAM with an additional 8 GB of extended RAM, which allows you to keep up to 27 apps in the background. It uses a powerful MediaTek Dimensity 900 processor to give you a smooth 5G experience, and its 4500 mAh battery with 44 W FlashCharge lets the phone’s battery last for a long time This smartphone has many camera features, so you can create vlogs, movies, and click portraits as you desire. The Funtouch OS 13, allows you to have a secure OS experience, in addition to that you can also enjoy personalised settings, privacy protection, and much more.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-01-07T19:40:36.422545",
      permission: 1,
      slug: "vivo-y100",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 20499.0,
      whishlist_status: "Login Required",
      variant_id: 5337,
      variant_name: "vivo Y100 5G (Twilight Gold, 128 GB) (8 GB RAM)",
      actual_price: 20499.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-Y100-Mobile-Phone-GOLD.jpg",
      color_variant_id: 1477,
      color_variant_name: "Twilight Gold",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 96,
      other_variant_name: "8 GB",
      stock_sataus: "In-stock",
      id: 3344,
      Meta_Title: "VIVO Y100 ",
      Meta_Keyword: "VIVO Y100 ",
      Meta_Description: "VIVO Y100 ",
      title: "VIVO Y100 ",
      HSN: "8517",
      description:
        "The Vivo Y100 5G features colour-changing fluorite AG glass that changes colour with changes in environment and time. The 64 MP OIS anti-shake camera helps to take steady and cinematic images without any hassle. This smartphone has 8 GB RAM with an additional 8 GB of extended RAM, which allows you to keep up to 27 apps in the background. It uses a powerful MediaTek Dimensity 900 processor to give you a smooth 5G experience, and its 4500 mAh battery with 44 W FlashCharge lets the phone’s battery last for a long time This smartphone has many camera features, so you can create vlogs, movies, and click portraits as you desire. The Funtouch OS 13, allows you to have a secure OS experience, in addition to that you can also enjoy personalised settings, privacy protection, and much more.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-01-07T19:40:36.422545",
      permission: 1,
      slug: "vivo-y100",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 17999.0,
      whishlist_status: "Login Required",
      variant_id: 5357,
      variant_name: "SAMSUNG Galaxy A14 5G (Dark Red, 128 GB) (8 GB RAM)",
      actual_price: 17999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/samsung-galaxy-a14-5g-dark-red-4gb-128gb-front-back-view-min_3ocw0SE.webp",
      color_variant_id: 1438,
      color_variant_name: "Dark Red ",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 96,
      other_variant_name: "8 GB",
      stock_sataus: "In-stock",
      id: 3353,
      Meta_Title: "SAMSUNG GALAXY A14 5G ",
      Meta_Keyword: "SAMSUNG GALAXY A14 5G ",
      Meta_Description: "SAMSUNG GALAXY A14 5G ",
      title: "SAMSUNG Galaxy A14 5G ",
      HSN: "85171300",
      description:
        "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-06-21T15:54:07.772549",
      permission: 1,
      slug: "samsung-galaxy-a14-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 185,
      sub_category: "Samsung ",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 220,
      brand_name: "Samsung",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 13499.0,
      whishlist_status: "Login Required",
      variant_id: 5358,
      variant_name: "SAMSUNG Galaxy A14 5G (Light Green, 64 GB)  (4 GB RAM)",
      actual_price: 13499.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Samsung-Galaxy-A14-5G-Light-Green-4GB-128GB-front-back-view-min_XwUIITG.webp",
      color_variant_id: 1484,
      color_variant_name: "Light Green ",
      storage_variant_id: 169,
      storage_variant_name: "64 GB",
      other_variant_id: 97,
      other_variant_name: "4 GB",
      stock_sataus: "In-stock",
      id: 3353,
      Meta_Title: "SAMSUNG GALAXY A14 5G ",
      Meta_Keyword: "SAMSUNG GALAXY A14 5G ",
      Meta_Description: "SAMSUNG GALAXY A14 5G ",
      title: "SAMSUNG Galaxy A14 5G ",
      HSN: "85171300",
      description:
        "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-06-21T15:54:07.772549",
      permission: 1,
      slug: "samsung-galaxy-a14-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 185,
      sub_category: "Samsung ",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 220,
      brand_name: "Samsung",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 13499.0,
      whishlist_status: "Login Required",
      variant_id: 5359,
      variant_name: "SAMSUNG Galaxy A14 5G (Dark Red, 64 GB)  (4 GB RAM)",
      actual_price: 13499.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/samsung-galaxy-a14-5g-dark-red-4gb-128gb-front-back-view-min_eDHqOU4.webp",
      color_variant_id: 1438,
      color_variant_name: "Dark Red ",
      storage_variant_id: 169,
      storage_variant_name: "64 GB",
      other_variant_id: 97,
      other_variant_name: "4 GB",
      stock_sataus: "In-stock",
      id: 3353,
      Meta_Title: "SAMSUNG GALAXY A14 5G ",
      Meta_Keyword: "SAMSUNG GALAXY A14 5G ",
      Meta_Description: "SAMSUNG GALAXY A14 5G ",
      title: "SAMSUNG Galaxy A14 5G ",
      HSN: "85171300",
      description:
        "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-06-21T15:54:07.772549",
      permission: 1,
      slug: "samsung-galaxy-a14-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 185,
      sub_category: "Samsung ",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 220,
      brand_name: "Samsung",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 13499.0,
      whishlist_status: "Login Required",
      variant_id: 5360,
      variant_name: "SAMSUNG Galaxy A14 5G (Black, 64 GB) (4 GB RAM)",
      actual_price: 13499.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/samsung-galaxy-a14-5g-black-128gb-4gb-ram-front-back-view-min_0VK9CxE.webp",
      color_variant_id: 1401,
      color_variant_name: "Black ",
      storage_variant_id: 169,
      storage_variant_name: "64 GB",
      other_variant_id: 97,
      other_variant_name: "4 GB",
      stock_sataus: "In-stock",
      id: 3353,
      Meta_Title: "SAMSUNG GALAXY A14 5G ",
      Meta_Keyword: "SAMSUNG GALAXY A14 5G ",
      Meta_Description: "SAMSUNG GALAXY A14 5G ",
      title: "SAMSUNG Galaxy A14 5G ",
      HSN: "85171300",
      description:
        "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-06-21T15:54:07.772549",
      permission: 1,
      slug: "samsung-galaxy-a14-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 185,
      sub_category: "Samsung ",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 220,
      brand_name: "Samsung",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 15999.0,
      whishlist_status: "Login Required",
      variant_id: 5361,
      variant_name: "SAMSUNG Galaxy A14 5G (Dark Red, 128 GB)  (6 GB RAM)",
      actual_price: 15999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/samsung-galaxy-a14-5g-dark-red-4gb-128gb-front-back-view-min.webp",
      color_variant_id: 1438,
      color_variant_name: "Dark Red ",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 98,
      other_variant_name: "6 GB",
      stock_sataus: "In-stock",
      id: 3353,
      Meta_Title: "SAMSUNG GALAXY A14 5G ",
      Meta_Keyword: "SAMSUNG GALAXY A14 5G ",
      Meta_Description: "SAMSUNG GALAXY A14 5G ",
      title: "SAMSUNG Galaxy A14 5G ",
      HSN: "85171300",
      description:
        "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-06-21T15:54:07.772549",
      permission: 1,
      slug: "samsung-galaxy-a14-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 185,
      sub_category: "Samsung ",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 220,
      brand_name: "Samsung",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 15999.0,
      whishlist_status: "Login Required",
      variant_id: 5362,
      variant_name: "SAMSUNG Galaxy A14 5G (Black, 128 GB) (6 GB RAM)",
      actual_price: 15999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/samsung-galaxy-a14-5g-black-128gb-4gb-ram-front-back-view-min_2sGxNYC.webp",
      color_variant_id: 1401,
      color_variant_name: "Black ",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 98,
      other_variant_name: "6 GB",
      stock_sataus: "In-stock",
      id: 3353,
      Meta_Title: "SAMSUNG GALAXY A14 5G ",
      Meta_Keyword: "SAMSUNG GALAXY A14 5G ",
      Meta_Description: "SAMSUNG GALAXY A14 5G ",
      title: "SAMSUNG Galaxy A14 5G ",
      HSN: "85171300",
      description:
        "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-06-21T15:54:07.772549",
      permission: 1,
      slug: "samsung-galaxy-a14-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 185,
      sub_category: "Samsung ",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 220,
      brand_name: "Samsung",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 15999.0,
      whishlist_status: "Login Required",
      variant_id: 5363,
      variant_name: "SAMSUNG Galaxy A14 5G (Light Green, 128 GB) (6 GB RAM)",
      actual_price: 15999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Samsung-Galaxy-A14-5G-Light-Green-4GB-128GB-front-back-view-min_SuQoFMv.webp",
      color_variant_id: 1484,
      color_variant_name: "Light Green ",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 98,
      other_variant_name: "6 GB",
      stock_sataus: "In-stock",
      id: 3353,
      Meta_Title: "SAMSUNG GALAXY A14 5G ",
      Meta_Keyword: "SAMSUNG GALAXY A14 5G ",
      Meta_Description: "SAMSUNG GALAXY A14 5G ",
      title: "SAMSUNG Galaxy A14 5G ",
      HSN: "85171300",
      description:
        "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-06-21T15:54:07.772549",
      permission: 1,
      slug: "samsung-galaxy-a14-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 185,
      sub_category: "Samsung ",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 220,
      brand_name: "Samsung",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 17999.0,
      whishlist_status: "Login Required",
      variant_id: 5364,
      variant_name: "SAMSUNG Galaxy A14 5G (Black, 128 GB) (8 GB RAM)",
      actual_price: 17999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/samsung-galaxy-a14-5g-black-128gb-4gb-ram-front-back-view-min.webp",
      color_variant_id: 1401,
      color_variant_name: "Black ",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 96,
      other_variant_name: "8 GB",
      stock_sataus: "In-stock",
      id: 3353,
      Meta_Title: "SAMSUNG GALAXY A14 5G ",
      Meta_Keyword: "SAMSUNG GALAXY A14 5G ",
      Meta_Description: "SAMSUNG GALAXY A14 5G ",
      title: "SAMSUNG Galaxy A14 5G ",
      HSN: "85171300",
      description:
        "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-06-21T15:54:07.772549",
      permission: 1,
      slug: "samsung-galaxy-a14-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 185,
      sub_category: "Samsung ",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 220,
      brand_name: "Samsung",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 17999.0,
      whishlist_status: "Login Required",
      variant_id: 5365,
      variant_name: "SAMSUNG Galaxy A14 5G (Light Green, 128 GB) (8 GB RAM)",
      actual_price: 17999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Samsung-Galaxy-A14-5G-Light-Green-4GB-128GB-front-back-view-min.webp",
      color_variant_id: 1484,
      color_variant_name: "Light Green ",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 96,
      other_variant_name: "8 GB",
      stock_sataus: "In-stock",
      id: 3353,
      Meta_Title: "SAMSUNG GALAXY A14 5G ",
      Meta_Keyword: "SAMSUNG GALAXY A14 5G ",
      Meta_Description: "SAMSUNG GALAXY A14 5G ",
      title: "SAMSUNG Galaxy A14 5G ",
      HSN: "85171300",
      description:
        "With the feature-rich Samsung Galaxy A14 5G smartphone, you can multitask without lag and have flawless connectivity. The Galaxy A14 5G provides you with the precision and speed you need to be working with ease with its Octa-core processor and 5G connectivity. You also have a large area of view and operate on the 16.72 cm (6.6) Infinity-V Display of the Galaxy A14 5G. The 50 MP primary camera on this phone can also be used to capture beautiful landscape images. Additionally, the Dimension camera gives your photos a remarkable depth, while the Macro camera captures minute details.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-06-21T15:54:07.772549",
      permission: 1,
      slug: "samsung-galaxy-a14-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 185,
      sub_category: "Samsung ",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 220,
      brand_name: "Samsung",
      store_id: 1,
    },
    {
      quantity: "50",
      price: 27990.0,
      whishlist_status: "Login Required",
      variant_id: 5378,
      variant_name: "vivo V25 5G (Surfing Blue, 128 GB)  (8 GB RAM)",
      actual_price: 27990.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-5g-surfing-blue-128gb-8gb-ram-Front-Back-View_qWNtOZh.webp",
      color_variant_id: 1489,
      color_variant_name: "Surfing Blue",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 96,
      other_variant_name: "8 GB",
      stock_sataus: "In-stock",
      id: 3357,
      Meta_Title: "VIVO V25 5G",
      Meta_Keyword: "VIVO V25 5G",
      Meta_Description: "VIVO V25 5G",
      title: "VIVO V25 5G",
      HSN: "85171300",
      description:
        "The innovative Vivo V25 5G smartphone is designed to wow you from the inside out. It allows you to discover exciting options and capture timeless beauty. The 6 nm CPU and dual-mode 5G in this phone enable a fluid user experience. Additionally, the superb 50 MP Eye AF camera on this phone allows you to take mesmerising photos with flawless imagery. Furthermore, you can store everything you want and treasure your precious moments, thanks to an internal storage capacity of up to 256 GB and a memory expansion capability of up to 1 TB.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-05T19:00:35.677355",
      permission: 1,
      slug: "vivo-v25-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 27999.0,
      whishlist_status: "Login Required",
      variant_id: 5379,
      variant_name: "vivo V25 5G (Elegant Black, 128 GB)  (8 GB RAM)",
      actual_price: 27999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-5g-elegant-blue-128gb-8gb-ram-Front-Back-View_2iwgxIn.webp",
      color_variant_id: 1490,
      color_variant_name: "Elegant Black",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 96,
      other_variant_name: "8 GB",
      stock_sataus: "In-stock",
      id: 3357,
      Meta_Title: "VIVO V25 5G",
      Meta_Keyword: "VIVO V25 5G",
      Meta_Description: "VIVO V25 5G",
      title: "VIVO V25 5G",
      HSN: "85171300",
      description:
        "The innovative Vivo V25 5G smartphone is designed to wow you from the inside out. It allows you to discover exciting options and capture timeless beauty. The 6 nm CPU and dual-mode 5G in this phone enable a fluid user experience. Additionally, the superb 50 MP Eye AF camera on this phone allows you to take mesmerising photos with flawless imagery. Furthermore, you can store everything you want and treasure your precious moments, thanks to an internal storage capacity of up to 256 GB and a memory expansion capability of up to 1 TB.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-05T19:00:35.677355",
      permission: 1,
      slug: "vivo-v25-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 31999.0,
      whishlist_status: "Login Required",
      variant_id: 5380,
      variant_name: "vivo V25 5G (Surfing Blue, 256 GB)  (12 GB RAM)",
      actual_price: 31999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-5g-surfing-blue-128gb-8gb-ram-Front-Back-View.webp",
      color_variant_id: 1489,
      color_variant_name: "Surfing Blue",
      storage_variant_id: 170,
      storage_variant_name: "256 GB",
      other_variant_id: 100,
      other_variant_name: "12 GB",
      stock_sataus: "In-stock",
      id: 3357,
      Meta_Title: "VIVO V25 5G",
      Meta_Keyword: "VIVO V25 5G",
      Meta_Description: "VIVO V25 5G",
      title: "VIVO V25 5G",
      HSN: "85171300",
      description:
        "The innovative Vivo V25 5G smartphone is designed to wow you from the inside out. It allows you to discover exciting options and capture timeless beauty. The 6 nm CPU and dual-mode 5G in this phone enable a fluid user experience. Additionally, the superb 50 MP Eye AF camera on this phone allows you to take mesmerising photos with flawless imagery. Furthermore, you can store everything you want and treasure your precious moments, thanks to an internal storage capacity of up to 256 GB and a memory expansion capability of up to 1 TB.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-05T19:00:35.677355",
      permission: 1,
      slug: "vivo-v25-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 31999.0,
      whishlist_status: "Login Required",
      variant_id: 5381,
      variant_name: "vivo V25 5G (Elegant Black, 256 GB)  (12 GB RAM)",
      actual_price: 31999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-5g-elegant-blue-128gb-8gb-ram-Front-Back-View.webp",
      color_variant_id: 1490,
      color_variant_name: "Elegant Black",
      storage_variant_id: 170,
      storage_variant_name: "256 GB",
      other_variant_id: 100,
      other_variant_name: "12 GB",
      stock_sataus: "In-stock",
      id: 3357,
      Meta_Title: "VIVO V25 5G",
      Meta_Keyword: "VIVO V25 5G",
      Meta_Description: "VIVO V25 5G",
      title: "VIVO V25 5G",
      HSN: "85171300",
      description:
        "The innovative Vivo V25 5G smartphone is designed to wow you from the inside out. It allows you to discover exciting options and capture timeless beauty. The 6 nm CPU and dual-mode 5G in this phone enable a fluid user experience. Additionally, the superb 50 MP Eye AF camera on this phone allows you to take mesmerising photos with flawless imagery. Furthermore, you can store everything you want and treasure your precious moments, thanks to an internal storage capacity of up to 256 GB and a memory expansion capability of up to 1 TB.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-05T19:00:35.677355",
      permission: 1,
      slug: "vivo-v25-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "50",
      price: 39999.0,
      whishlist_status: "Login Required",
      variant_id: 5382,
      variant_name: "vivo V25 Pro 5G (Sailing Blue, 256 GB)  (12 GB RAM)",
      actual_price: 39999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/vivo-v25-pro-sailing-blue-256gb-12gb-ram-front-back.webp",
      color_variant_id: 1491,
      color_variant_name: "Sailing Blue",
      storage_variant_id: 170,
      storage_variant_name: "256 GB",
      other_variant_id: 100,
      other_variant_name: "12 GB",
      stock_sataus: "In-stock",
      id: 3358,
      Meta_Title: "VIVO V25 PRO 5G",
      Meta_Keyword: "VIVO V25 PRO 5G",
      Meta_Description: "VIVO V25 PRO 5G",
      title: "VIVO V25 PRO 5G",
      HSN: "85171300",
      description:
        "With the innovative Vivo V25 Pro 5G smartphone, which is perfectly suited for multitaskers, you can effortlessly elevate your entertainment to a different extreme and enhance your productivity. This phone boosts your performance with its magnificent 16.66 cm (6.56) POLED display and quick 120 Hz refresh rate. Furthermore, you can take mesmerising pictures with outstanding graphics thanks to a fantastic back camera arrangement and a 32 MP front camera. Additionally, this phone meets all of your multitasking demands owing to its MediaTek Dimensity 1300 processor and 6 nm architecture.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-10T20:10:13.501446",
      permission: 1,
      slug: "vivo-v25-pro-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "20",
      price: 35999.0,
      whishlist_status: "Login Required",
      variant_id: 5383,
      variant_name: "vivo V25 Pro 5G (Pure Black, 128 GB)  (8 GB RAM)",
      actual_price: 35999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-pro-pure-black-256gb-12gb-ram-Front-Back-Side-View_Rak7qq9.webp",
      color_variant_id: 1492,
      color_variant_name: "Pure Black",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 96,
      other_variant_name: "8 GB",
      stock_sataus: "In-stock",
      id: 3358,
      Meta_Title: "VIVO V25 PRO 5G",
      Meta_Keyword: "VIVO V25 PRO 5G",
      Meta_Description: "VIVO V25 PRO 5G",
      title: "VIVO V25 PRO 5G",
      HSN: "85171300",
      description:
        "With the innovative Vivo V25 Pro 5G smartphone, which is perfectly suited for multitaskers, you can effortlessly elevate your entertainment to a different extreme and enhance your productivity. This phone boosts your performance with its magnificent 16.66 cm (6.56) POLED display and quick 120 Hz refresh rate. Furthermore, you can take mesmerising pictures with outstanding graphics thanks to a fantastic back camera arrangement and a 32 MP front camera. Additionally, this phone meets all of your multitasking demands owing to its MediaTek Dimensity 1300 processor and 6 nm architecture.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-10T20:10:13.501446",
      permission: 1,
      slug: "vivo-v25-pro-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "2",
      price: 35999.0,
      whishlist_status: "Login Required",
      variant_id: 5384,
      variant_name: "vivo V25 Pro 5G (Pure Black, 256 GB)  (12 GB RAM)",
      actual_price: 35999.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Vivo-v25-pro-pure-black-256gb-12gb-ram-Front-Back-Side-View.webp",
      color_variant_id: 1492,
      color_variant_name: "Pure Black",
      storage_variant_id: 170,
      storage_variant_name: "256 GB",
      other_variant_id: 100,
      other_variant_name: "12 GB",
      stock_sataus: "In-stock",
      id: 3358,
      Meta_Title: "VIVO V25 PRO 5G",
      Meta_Keyword: "VIVO V25 PRO 5G",
      Meta_Description: "VIVO V25 PRO 5G",
      title: "VIVO V25 PRO 5G",
      HSN: "85171300",
      description:
        "With the innovative Vivo V25 Pro 5G smartphone, which is perfectly suited for multitaskers, you can effortlessly elevate your entertainment to a different extreme and enhance your productivity. This phone boosts your performance with its magnificent 16.66 cm (6.56) POLED display and quick 120 Hz refresh rate. Furthermore, you can take mesmerising pictures with outstanding graphics thanks to a fantastic back camera arrangement and a 32 MP front camera. Additionally, this phone meets all of your multitasking demands owing to its MediaTek Dimensity 1300 processor and 6 nm architecture.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-10T20:10:13.501446",
      permission: 1,
      slug: "vivo-v25-pro-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 192,
      sub_category: "Vivo",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 232,
      brand_name: "VIVO",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 46400.0,
      whishlist_status: "Login Required",
      variant_id: 5386,
      variant_name: "APPLE iPhone 13 (Blue, 128 GB)",
      actual_price: 46400.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-iPhone-13-Smartphones-blue.jpg",
      color_variant_id: 1409,
      color_variant_name: "Blue",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: "",
      other_variant_name: "",
      stock_sataus: "In-stock",
      id: 3360,
      Meta_Title: "Apple iPhone 13",
      Meta_Keyword: "Apple iPhone 13",
      Meta_Description: "Apple iPhone 13",
      title: "Apple iPhone 13",
      HSN: "85171300",
      description:
        "<p>The iPhone 13 features a stylish design and innovative features that make it a delight to use. It is equipped with a Dual-camera system that adds an upgrade to the photos and videos that you take. It offers a big boost in battery so that you have enough time to watch content, game, and so on. And, the A15 Bionic helps load graphics-intensive games with ease.&nbsp;</p>",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2025-01-22T22:50:33.647504",
      permission: 1,
      slug: "apple-iphone-13",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 194,
      sub_category: "Apple",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 260,
      brand_name: "Apple",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 46400.0,
      whishlist_status: "Login Required",
      variant_id: 5388,
      variant_name: "APPLE iPhone 13 (Green, 128 GB)",
      actual_price: 46400.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-iPhone-13-Smartphones-GREEN.jpg",
      color_variant_id: 1494,
      color_variant_name: "Green",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: "",
      other_variant_name: "",
      stock_sataus: "In-stock",
      id: 3360,
      Meta_Title: "Apple iPhone 13",
      Meta_Keyword: "Apple iPhone 13",
      Meta_Description: "Apple iPhone 13",
      title: "Apple iPhone 13",
      HSN: "85171300",
      description:
        "<p>The iPhone 13 features a stylish design and innovative features that make it a delight to use. It is equipped with a Dual-camera system that adds an upgrade to the photos and videos that you take. It offers a big boost in battery so that you have enough time to watch content, game, and so on. And, the A15 Bionic helps load graphics-intensive games with ease.&nbsp;</p>",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2025-01-22T22:50:33.647504",
      permission: 1,
      slug: "apple-iphone-13",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 194,
      sub_category: "Apple",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 260,
      brand_name: "Apple",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 46400.0,
      whishlist_status: "Login Required",
      variant_id: 5389,
      variant_name: "APPLE iPhone 13 (Pink, 128 GB)",
      actual_price: 46400.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-MLPH3HN-A-SmartPhones-PINK.jpg",
      color_variant_id: 1495,
      color_variant_name: "Pink",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: "",
      other_variant_name: "",
      stock_sataus: "In-stock",
      id: 3360,
      Meta_Title: "Apple iPhone 13",
      Meta_Keyword: "Apple iPhone 13",
      Meta_Description: "Apple iPhone 13",
      title: "Apple iPhone 13",
      HSN: "85171300",
      description:
        "<p>The iPhone 13 features a stylish design and innovative features that make it a delight to use. It is equipped with a Dual-camera system that adds an upgrade to the photos and videos that you take. It offers a big boost in battery so that you have enough time to watch content, game, and so on. And, the A15 Bionic helps load graphics-intensive games with ease.&nbsp;</p>",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2025-01-22T22:50:33.647504",
      permission: 1,
      slug: "apple-iphone-13",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 194,
      sub_category: "Apple",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 260,
      brand_name: "Apple",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 46400.0,
      whishlist_status: "Login Required",
      variant_id: 5390,
      variant_name: "APPLE iPhone 13 (Starlight, 128 GB)",
      actual_price: 46400.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-MLPG3HN-A-SmartPhones-Starlight.jpg",
      color_variant_id: 1496,
      color_variant_name: "Starlight",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: "",
      other_variant_name: "",
      stock_sataus: "In-stock",
      id: 3360,
      Meta_Title: "Apple iPhone 13",
      Meta_Keyword: "Apple iPhone 13",
      Meta_Description: "Apple iPhone 13",
      title: "Apple iPhone 13",
      HSN: "85171300",
      description:
        "<p>The iPhone 13 features a stylish design and innovative features that make it a delight to use. It is equipped with a Dual-camera system that adds an upgrade to the photos and videos that you take. It offers a big boost in battery so that you have enough time to watch content, game, and so on. And, the A15 Bionic helps load graphics-intensive games with ease.&nbsp;</p>",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2025-01-22T22:50:33.647504",
      permission: 1,
      slug: "apple-iphone-13",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 194,
      sub_category: "Apple",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 260,
      brand_name: "Apple",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 46400.0,
      whishlist_status: "Login Required",
      variant_id: 5391,
      variant_name: "Apple iPhone 13 (Midnight, 128 GB)",
      actual_price: 46400.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-MLPF3HN-A-Smart-Phone-Midnight_Black.jpg",
      color_variant_id: 1497,
      color_variant_name: "Midnight",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: "",
      other_variant_name: "",
      stock_sataus: "In-stock",
      id: 3360,
      Meta_Title: "Apple iPhone 13",
      Meta_Keyword: "Apple iPhone 13",
      Meta_Description: "Apple iPhone 13",
      title: "Apple iPhone 13",
      HSN: "85171300",
      description:
        "<p>The iPhone 13 features a stylish design and innovative features that make it a delight to use. It is equipped with a Dual-camera system that adds an upgrade to the photos and videos that you take. It offers a big boost in battery so that you have enough time to watch content, game, and so on. And, the A15 Bionic helps load graphics-intensive games with ease.&nbsp;</p>",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2025-01-22T22:50:33.647504",
      permission: 1,
      slug: "apple-iphone-13",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 194,
      sub_category: "Apple",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 260,
      brand_name: "Apple",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 54900.0,
      whishlist_status: "Login Required",
      variant_id: 5399,
      variant_name: "APPLE iPhone 14 (RED, 128 GB)",
      actual_price: 54900.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-14-Plus-Red-Front-Back-01-01.webp",
      color_variant_id: 1493,
      color_variant_name: "Red",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: "",
      other_variant_name: "",
      stock_sataus: "In-stock",
      id: 3362,
      Meta_Title: "Apple iPhone 14",
      Meta_Keyword: "Apple iPhone 14",
      Meta_Description: "Apple iPhone 14",
      title: "Apple iPhone 14",
      HSN: "85171300",
      description: "<p>Apple iPhone 14</p>",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2025-01-18T18:25:43.062078",
      permission: 1,
      slug: "apple-iphone-14",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 194,
      sub_category: "Apple",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 260,
      brand_name: "Apple",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 54900.0,
      whishlist_status: "Login Required",
      variant_id: 5400,
      variant_name: "APPLE iPhone 14 (Blue, 128 GB)",
      actual_price: 54900.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-iphone-14-blue-512gb-Front-Back-View_1.webp",
      color_variant_id: 1409,
      color_variant_name: "Blue",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: "",
      other_variant_name: "",
      stock_sataus: "In-stock",
      id: 3362,
      Meta_Title: "Apple iPhone 14",
      Meta_Keyword: "Apple iPhone 14",
      Meta_Description: "Apple iPhone 14",
      title: "Apple iPhone 14",
      HSN: "85171300",
      description: "<p>Apple iPhone 14</p>",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2025-01-18T18:25:43.062078",
      permission: 1,
      slug: "apple-iphone-14",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 194,
      sub_category: "Apple",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 260,
      brand_name: "Apple",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 54900.0,
      whishlist_status: "Login Required",
      variant_id: 5401,
      variant_name: "APPLE iPhone 14 (Midnight, 128 GB)",
      actual_price: 54900.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-iphone-14-midnight-512gb-Front-Back-View.webp",
      color_variant_id: 1497,
      color_variant_name: "Midnight",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: "",
      other_variant_name: "",
      stock_sataus: "In-stock",
      id: 3362,
      Meta_Title: "Apple iPhone 14",
      Meta_Keyword: "Apple iPhone 14",
      Meta_Description: "Apple iPhone 14",
      title: "Apple iPhone 14",
      HSN: "85171300",
      description: "<p>Apple iPhone 14</p>",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2025-01-18T18:25:43.062078",
      permission: 1,
      slug: "apple-iphone-14",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 194,
      sub_category: "Apple",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 260,
      brand_name: "Apple",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 54900.0,
      whishlist_status: "Login Required",
      variant_id: 5402,
      variant_name: "APPLE iPhone 14 (Purple, 128 GB)",
      actual_price: 54900.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-iphone-14-512gb-purple-Front-Back-View.webp",
      color_variant_id: 1498,
      color_variant_name: "Purple",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: "",
      other_variant_name: "",
      stock_sataus: "In-stock",
      id: 3362,
      Meta_Title: "Apple iPhone 14",
      Meta_Keyword: "Apple iPhone 14",
      Meta_Description: "Apple iPhone 14",
      title: "Apple iPhone 14",
      HSN: "85171300",
      description: "<p>Apple iPhone 14</p>",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2025-01-18T18:25:43.062078",
      permission: 1,
      slug: "apple-iphone-14",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 194,
      sub_category: "Apple",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 260,
      brand_name: "Apple",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 54900.0,
      whishlist_status: "Login Required",
      variant_id: 5403,
      variant_name: "APPLE iPhone 14 (Starlight, 128 GB)",
      actual_price: 54900.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/Apple-14-Plus-Starlight-Front-Back-01.webp",
      color_variant_id: 1496,
      color_variant_name: "Starlight",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: "",
      other_variant_name: "",
      stock_sataus: "In-stock",
      id: 3362,
      Meta_Title: "Apple iPhone 14",
      Meta_Keyword: "Apple iPhone 14",
      Meta_Description: "Apple iPhone 14",
      title: "Apple iPhone 14",
      HSN: "85171300",
      description: "<p>Apple iPhone 14</p>",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2025-01-18T18:25:43.062078",
      permission: 1,
      slug: "apple-iphone-14",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 194,
      sub_category: "Apple",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 260,
      brand_name: "Apple",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 54900.0,
      whishlist_status: "Login Required",
      variant_id: 5404,
      variant_name: "APPLE iPhone 14 (Yellow, 128 GB)",
      actual_price: 54900.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/apple-iphone-14-yellow-256gb-front-back-view_kPLDTWI.webp",
      color_variant_id: 1499,
      color_variant_name: "Yellow",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: "",
      other_variant_name: "",
      stock_sataus: "In-stock",
      id: 3362,
      Meta_Title: "Apple iPhone 14",
      Meta_Keyword: "Apple iPhone 14",
      Meta_Description: "Apple iPhone 14",
      title: "Apple iPhone 14",
      HSN: "85171300",
      description: "<p>Apple iPhone 14</p>",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2025-01-18T18:25:43.062078",
      permission: 1,
      slug: "apple-iphone-14",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 194,
      sub_category: "Apple",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 260,
      brand_name: "Apple",
      store_id: 1,
    },
    {
      quantity: "100",
      price: 8299.0,
      whishlist_status: "Login Required",
      variant_id: 5480,
      variant_name: "Tecno Spark 9 (Infinity Black ,128GB+6GB)",
      actual_price: 8299.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/91J1pz6vBcL.webp",
      color_variant_id: 1401,
      color_variant_name: "Black ",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 98,
      other_variant_name: "6 GB",
      stock_sataus: "In-stock",
      id: 3382,
      Meta_Title: "Tecno Spark 9",
      Meta_Keyword: "Tecno Spark 9",
      Meta_Description: "Tecno Spark 9",
      title: "Tecno Spark 9",
      HSN: "8517",
      description:
        "Tecno has again created a featureful, yet budget device so that you can carry on your day-to-day tasks without any trouble. The Tecno Spark 9 64GB is equipped with a robust set of configurations that are backed by a large battery, attractive display, and vast internal storage. The brand is using a 6.6-inches IPS LCD display in the Tecno Spark 9, which also has an aspect ratio of 20:9. The resolution of this display is 1600 x 720 pixels and its pixel density is 266ppi. Moreover, it also gives a fluid scrolling experience through its 90Hz refresh rate. A single 13MP Wide Angle Main Lens has been provided by the brand. It is installed on the rear side of the Tecno Spark 9 and built with an aperture of f/1.85. Dual LED Flash, HDR mode, Digital Zoom, ISO Control, etc are other features of this camera. With its 8MP f/2 resolution front camera, users can also capture some good portraits as well as make video calls. Tecno Spark 9 64GB is equipped with a MediaTek Helio G37 chipset, along with an Octa-core (2.3GHz, Quad-core, Cortex A53 and.8GHz, Quad-core, 1, Cortex A53) processor. There is also a 3GB LPDDR4X RAM and a PowerVR GE8320 GPU installed in the device that makes the smartphone run at great speed and, at the same time, display good graphics. There is a 5000mAh battery installed inside the Tecno Spark 9 which belongs to the Li-Polymer family.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-05-23T11:16:53.810092",
      permission: 1,
      slug: "tecno-spark-9",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 179,
      sub_category: "Tecno",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 224,
      brand_name: "Tecno",
      store_id: 1,
    },
    {
      quantity: "100",
      price: 8745.0,
      whishlist_status: "Login Required",
      variant_id: 5490,
      variant_name: "Tecno Spark 8C (Magnet Black, 64GB+4GB)",
      actual_price: 8745.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/New_Crazzy_69_Ip39UkC_5RnTSLN.jpg",
      color_variant_id: 1511,
      color_variant_name: "Magnet Black",
      storage_variant_id: 169,
      storage_variant_name: "64 GB",
      other_variant_id: 97,
      other_variant_name: "4 GB",
      stock_sataus: "In-stock",
      id: 3384,
      Meta_Title: "Tecno Spark 8C",
      Meta_Keyword: "Tecno Spark 8C",
      Meta_Description: "Tecno Spark 8C",
      title: "Tecno Spark 8C",
      HSN: "8517",
      description:
        "Tecno Spark 8C is bezel-less IPS LCD gets a waterdrop notch on the top, housing the front camera. Also, this device promises attractive visuals with a refresh rate of 90Hz, 720 x 1612 pixels and an aspect ratio of 20:9. Lastly, the available pixel density stands at 267ppi. There is a single 13MP f/1.8 Wide Angle Primary Camera present on the backside of the smartphone accompanied by a Dual LED Flash and 77 degrees of field view. An 8MP Front Camera takes care of the selfie game. Unisoc T606 chipset and a 3GB RAM takes care of the operational part accompanied by an Octa-core processor layout combining Cortex A75 Dual-core and Cortex A55 Hexa core, running at a clock speed of 1.6GHz (Max). A 5000mAh Li-Polymer battery is here to get you going seamlessly once 100% charged. You can carry on throughout the day, making back to back calls to clients, friends and family members. The 64GB expandable storage space is made available within Tecno Spark 8C. It can be expanded up to a limit of 256GB. Connectivity-wise, Bluetooth, Mobile Hotspot, NFC, Wi-Fi and USB OTG are made available. You can make voice and video calls over 4G VoLTE networks and get the most out of your daily life seamlessly.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2023-07-18T20:08:09.599175",
      permission: 1,
      slug: "tecno-spark-8c",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 179,
      sub_category: "Tecno",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 224,
      brand_name: "Tecno",
      store_id: 1,
    },
    {
      quantity: "100",
      price: 9135.0,
      whishlist_status: "Login Required",
      variant_id: 5491,
      variant_name: "Tecno Spark 8P (Atlantic Blue , 64GB+4GB)",
      actual_price: 9135.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/New_crazzyhub_2_14_iPh9xe5.jpg",
      color_variant_id: 1512,
      color_variant_name: "Atlantic Blue ",
      storage_variant_id: 169,
      storage_variant_name: "64 GB",
      other_variant_id: 97,
      other_variant_name: "4 GB",
      stock_sataus: "In-stock",
      id: 3385,
      Meta_Title: "Tecno Spark 8P",
      Meta_Keyword: "Tecno Spark 8P",
      Meta_Description: "Tecno Spark 8P",
      title: "Tecno Spark 8P",
      HSN: "8517",
      description:
        "Tecno Spark 8P will help you out with daily operations and seamless entertainment on the go. The brand has also loaded an amazing set of cameras on both ends backed by a powerful battery layout and steady processor setup to get you running throughout the day. Further, Tecno has incorporated a fingerprint sensor on the rear side, facilitating comprehensive protection from external intruders. Tecno Spark 8P features a 6.6 inches FHD+ IPS LCD comprising a pixel density of 400ppi, an aspect ratio of 20:9 and a resolution of 1080 x 2408 pixels. The smartphone also gets a bezel-less display along with a waterdrop notch, housing the selfie-shooting lens. There is a dual-camera setup on the backside of the device, which includes a 50MP f/1.6 Primary Camera and a 2MP f/2.4 Depth Camera. Inbuilt camera functionalities include Autofocus, Quad-LED Flash, ISO Control, Exposure Compensation, Face Detection, 120FPS Slow Motion, Time Lapse. On the front side, Tecno has provided an 8MP f/2.0 Primary Camera equipped with Dual LED Flash. Tecno Spark 8P is configured with a MediaTek Helio G85 chipset and a Mali-G52 MC2 GPU. It also includes an Octa-core Cortex A75 and Cortex A55 processor layout, running at a maximum speed of 2GHz. A 4GB RAM takes care of the overall multi-tasking experience. There is a 5000mAh Li-Polymer battery placed within the smartphone which is non-removable by nature.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2023-07-18T20:08:00.520267",
      permission: 1,
      slug: "tecno-spark-8p",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 179,
      sub_category: "Tecno",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 224,
      brand_name: "Tecno",
      store_id: 1,
    },
    {
      quantity: "100",
      price: 10990.0,
      whishlist_status: "Login Required",
      variant_id: 5492,
      variant_name: "Tecno Pova Neo (Sprint Blue , 128GB+6GB)",
      actual_price: 10990.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/New_crazzyhub_2_10_OEvD2V0.jpg",
      color_variant_id: 1513,
      color_variant_name: "Sprint Blue ",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 98,
      other_variant_name: "6 GB",
      stock_sataus: "In-stock",
      id: 3386,
      Meta_Title: "Tecno Pova Neo",
      Meta_Keyword: "Tecno Pova Neo",
      Meta_Description: "Tecno Pova Neo",
      title: "Tecno Pova Neo",
      HSN: "8517",
      description:
        "Tecno Pova Neo is a compact performer incorporated with a wide range of brilliant specs under the hood. It is all set to offer a fulfilling experience regarding gaming, photography and the operational needs of individual users.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2023-07-18T20:07:52.440701",
      permission: 1,
      slug: "tecno-pova-neo",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 179,
      sub_category: "Tecno",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 224,
      brand_name: "Tecno",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 15690.0,
      whishlist_status: "Login Required",
      variant_id: 5495,
      variant_name: "Tecno Pova Neo 5G (Greek Blue, 128GB) (6GB RAM)",
      actual_price: 15690.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/71H2SdmX26L_1wPpqrs.jpg",
      color_variant_id: 1515,
      color_variant_name: "Geek Blue",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 98,
      other_variant_name: "6 GB",
      stock_sataus: "In-stock",
      id: 3389,
      Meta_Title: "Tecno Pova Neo (5G)",
      Meta_Keyword: "Tecno Pova Neo (5G)",
      Meta_Description: "Tecno Pova Neo (5G)",
      title: "Tecno Pova Neo (5G)",
      HSN: "8517",
      description:
        "The Tecno Pova Neo 5G is a pretty decent device that comes with a set of specifications that will help you to carry out your day-to-day tasks comfortably. Tecno has offered a massive 6000mAh battery so that you can run it for prolonged hours. A 6.8-inches IPS LCD comes on the front side of the Tecno Pova Neo 5G and it offers a resolution of 2460 x 1080 pixels and a pixel density of 395ppi. The refresh rate of this display is 120Hz and it is built with an aspect ratio of 20:9. There is only a single 50MP camera available on the back surface of the Tecno Pova Neo 5G. This camera has an f/1.6 aperture and it comes with a Quad-LED Flash. Tecno has also installed an 8MP resolution camera on the front side. This front camera has an aperture of f/2.0 and it also comes with a Dual LED Flash. The Tecno Pova Neo 5G ensures consistent and quick performance with the help of its MediaTek Dimensity 810 MT6833 chipset, 4GB LPDDR4X RAM and an Eight-core processor featuring a layout of Cortex A76 and Cortex A55. Moreover, a Mali-G57 MC2 GPU is also present inside this smartphone. The 6000mAh Li-Polymer battery of the Tecno Pova Neo 5G promises to run it for an entire day. To charge this battery, a Flash Charging mechanism of 18W is also available in it.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-26T19:59:03.894469",
      permission: 1,
      slug: "tecno-pova-neo-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 179,
      sub_category: "Tecno",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 224,
      brand_name: "Tecno",
      store_id: 1,
    },
    {
      quantity: "10",
      price: 15499.0,
      whishlist_status: "Login Required",
      variant_id: 5496,
      variant_name: "Tecno Pova Neo 5G (Sapphire Black, 128 GB)  (4 GB RAM)",
      actual_price: 15499.0,
      image:
        "https://crazzyhub.s3.amazonaws.com/media/product_variant/tecno-pova-neo-5g-sapphire-black-128-gb-4-gb-ram--1000x1000_y4lkmjH.webp",
      color_variant_id: "",
      color_variant_name: "black",
      storage_variant_id: 168,
      storage_variant_name: "128 GB",
      other_variant_id: 97,
      other_variant_name: "4 GB",
      stock_sataus: "In-stock",
      id: 3389,
      Meta_Title: "Tecno Pova Neo (5G)",
      Meta_Keyword: "Tecno Pova Neo (5G)",
      Meta_Description: "Tecno Pova Neo (5G)",
      title: "Tecno Pova Neo (5G)",
      HSN: "8517",
      description:
        "The Tecno Pova Neo 5G is a pretty decent device that comes with a set of specifications that will help you to carry out your day-to-day tasks comfortably. Tecno has offered a massive 6000mAh battery so that you can run it for prolonged hours. A 6.8-inches IPS LCD comes on the front side of the Tecno Pova Neo 5G and it offers a resolution of 2460 x 1080 pixels and a pixel density of 395ppi. The refresh rate of this display is 120Hz and it is built with an aspect ratio of 20:9. There is only a single 50MP camera available on the back surface of the Tecno Pova Neo 5G. This camera has an f/1.6 aperture and it comes with a Quad-LED Flash. Tecno has also installed an 8MP resolution camera on the front side. This front camera has an aperture of f/2.0 and it also comes with a Dual LED Flash. The Tecno Pova Neo 5G ensures consistent and quick performance with the help of its MediaTek Dimensity 810 MT6833 chipset, 4GB LPDDR4X RAM and an Eight-core processor featuring a layout of Cortex A76 and Cortex A55. Moreover, a Mali-G57 MC2 GPU is also present inside this smartphone. The 6000mAh Li-Polymer battery of the Tecno Pova Neo 5G promises to run it for an entire day. To charge this battery, a Flash Charging mechanism of 18W is also available in it.",
      arriving_soon: false,
      show_for_user: true,
      is_bestseller: false,
      admin_permission: "Approved",
      lastedit_date: "2024-04-26T19:59:03.894469",
      permission: 1,
      slug: "tecno-pova-neo-5g",
      main_category_id: 28,
      main_category: "Mobiles & Tablets",
      sub_category_id: 179,
      sub_category: "Tecno",
      sub_sub_category_id: "",
      sub_sub_category: "",
      brand_id: 224,
      brand_name: "Tecno",
      store_id: 1,
    },
  ];

  const [search, setSearch] = useState(product_list);
  const [data, setData] = useState({ min: 0, max: 0 });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setData((prevData) => ({ ...prevData, [name]: value }));
  };

  const variant = [
    { ram: '4 GB' },
    { ram: '8 GB' },
    { ram: '12 GB' },
    { ram: '16 GB' }
  ];

  const handleSearch = (e) => {
    e.preventDefault();
    const filtered = product_list.filter((i) => i.price > data.min && i.price < data.max);
    setSearch(filtered);
  };

  const handleClear = (e) => {
    e.preventDefault();
    setSearch(product_list);
    setData({ min: 0, max: 0 });
  };

  const handleBrand = (value) => {
    const filtered = product_list.filter((data) => data.brand_name === value);
    setSearch(filtered);
  };

  const handleRam = (pro) => {
    const variant_rom = product_list.filter((item) => item.other_variant_name === pro);
    setSearch(variant_rom);
  };

  const handleColorVariant = (val) => {
    const color = product_list.filter((d) => d.color_variant_name === val);
    setSearch(color);
  };

  const [open, setOpen] = useState(false);

  const toggleDrawer = (newOpen) => () => {
    setOpen(newOpen);
  };

  return (

    <>
    <div className="flex flex-col lg:flex-row w-full gap-5 h-full bg-gray-100 p-5 lg:p-10">
      {/* Sidebar */}
      <div className="w-full lg:w-[20vw] bg-gray-200 p-5 lg:p-10 rounded-lg shadow-md">
        <p className="text-xl lg:text-2xl font-semibold mb-4">Search to Price</p>
        <label className="font-semibold">Minimum Price</label>
        <input className="w-full px-4 py-2 rounded-lg bg-gray-300 outline-none mb-2" value={data?.min} onChange={handleChange} type="text" name="min" />
        <label className="font-semibold">Maximum Price</label>
        <input className="w-full px-4 py-2 rounded-lg bg-gray-300 outline-none mb-4" value={data?.max} onChange={handleChange} type="text" name="max" />
        
        <div className="flex gap-x-3">
          <button className="w-1/2 px-4 py-2 rounded-lg bg-blue-500 mt-3 text-white font-semibold hover:bg-blue-600" onClick={handleSearch}>Search</button>
          <button className="w-1/2 px-4 py-2 rounded-lg bg-red-500 mt-3 text-white font-semibold hover:bg-red-600" onClick={handleClear}>Clear</button>
        </div>
        
        <div className="flex flex-col mt-4 gap-y-2">
          {["Samsung", "Apple", "Tecno"].map((brand) => (
            <button key={brand} className="w-full px-4 py-2 rounded-lg bg-blue-500 text-white font-semibold hover:bg-blue-600" onClick={() => handleBrand(brand)}>{brand}</button>
          ))}
        </div>
        
        <div className="flex gap-2 flex-wrap mt-4">
          {variant.map((i) => (
            <button key={i.ram} className="px-4 py-2 rounded-lg bg-blue-500 text-white font-semibold hover:bg-blue-600" onClick={() => handleRam(i.ram)}>{i.ram}</button>
          ))}
        </div>

        <div className="w-full flex flex-wrap justify-between mt-4">
          {product_list?.map((i) => (
            <button key={i.color_variant_name} className="py-2 rounded-lg bg-blue-500 mt-3 text-white w-[40%] hover:bg-red-600 font-semibold" onClick={() => handleColorVariant(i.color_variant_name)}>{i.color_variant_name}</button>
          ))}
        </div>

        

      </div>
      

     

      {/* Product Display */}
      <div className="w-full lg:w-[80vw] flex flex-wrap gap-5 justify-center">
        {search.length > 0 ? search.map((i) => (
          <div key={i.variant_name} className="w-full sm:w-[48%] md:w-[30%] lg:w-[18%] bg-white border border-gray-300 rounded-lg shadow-md overflow-hidden">
            <div className="bg-[#defed9] flex justify-center p-4">
              <img className="h-40 object-contain" src={i.image} alt={i.variant_name} />
            </div>
            <div className="p-3">
              <p className="text-sm font-semibold">{i.variant_name}</p>
              <div className="mt-2 flex justify-between items-center">
                <div>
                  <p className="text-gray-600 text-xs">{i.quantity}</p>
                  <p className="text-green-600 font-bold">{i.price}</p>
                  <p className="line-through text-gray-600 text-xs">{i.actual_price}</p>
                </div>
                <button className="bg-green-600 hover:bg-orange-500 px-4 py-1 text-white rounded-lg font-semibold">ADD</button>
              </div>
            </div>
          </div>
        )) : (
          <div className="h-[80vh] flex items-center justify-center w-full">
            <img src="https://www.shutterstock.com/image-vector/no-item-found-vector-filled-260nw-2087433073.jpg" alt="No items found" />
          </div>
        )}
      </div>
    </div>
    </> );
};

export default Mobile;